# Generated by Django 3.1.7 on 2021-03-28 07:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210328_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 28, 7, 31, 29, 751307, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 28, 7, 31, 29, 750311, tzinfo=utc), null=True),
        ),
    ]
